-- MySQL Script generated by MySQL Workbench
-- Mon 12 Jul 2021 03:49:45 PM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema intelliMerge_replication
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema intelliMerge_replication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `intelliMerge_replication` DEFAULT CHARACTER SET utf8 ;
USE `intelliMerge_replication` ;

-- -----------------------------------------------------
-- Table `intelliMerge_replication`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intelliMerge_replication`.`project` ;

CREATE TABLE IF NOT EXISTS `intelliMerge_replication`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(2000) NOT NULL,
  `name` VARCHAR(100) NULL,
  `is_done` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intelliMerge_replication`.`merge_commit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intelliMerge_replication`.`merge_commit` ;

CREATE TABLE IF NOT EXISTS `intelliMerge_replication`.`merge_commit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commit_hash` CHAR(40) NOT NULL,
  `is_conflicting` TINYINT(1) NOT NULL,
  `parent_1` CHAR(40) NOT NULL,
  `parent_2` CHAR(40) NOT NULL,
  `project_id` INT NOT NULL,
  `timestamp` MEDIUMTEXT NULL,
  `is_done` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`, `project_id`),
  UNIQUE INDEX `commit_hash_UNIQUE` (`commit_hash` ASC),
  INDEX `fk_merge_commit_project_idx` (`project_id` ASC),
  CONSTRAINT `fk_merge_commit_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `intelliMerge_replication`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intelliMerge_replication`.`merge_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intelliMerge_replication`.`merge_result` ;

CREATE TABLE IF NOT EXISTS `intelliMerge_replication`.`merge_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `merge_tool` VARCHAR(45) NOT NULL,
  `total_conflicts` INT NOT NULL,
  `total_conflicting_loc` INT NOT NULL,
  `total_diff_files` INT NOT NULL,
  `auto_merged_precision` DOUBLE NOT NULL,
  `auto_merged_recall` DOUBLE NOT NULL,
  `runtime` MEDIUMTEXT NOT NULL,
  `total_auto_merged_loc` INT NOT NULL,
  `total_manual_merged_loc` INT NOT NULL,
  `total_same_loc_merged` INT NOT NULL,
  `total_same_loc_manual` INT NOT NULL,
  `merge_commit_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `merge_commit_id`, `project_id`),
  INDEX `fk_merged_result_merge_commit1_idx` (`merge_commit_id` ASC, `project_id` ASC),
  CONSTRAINT `fk_conflicting_java_file_merge_commit1`
    FOREIGN KEY (`merge_commit_id` , `project_id`)
    REFERENCES `intelliMerge_replication`.`merge_commit` (`id` , `project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `intelliMerge_replication`.`refactoring_conflict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intelliMerge_replication`.`refactoring_conflict` ;

-- -----------------------------------------------------
-- Table `intelliMerge_replication`.`conflicting_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intelliMerge_replication`.`conflicting_file` ;

CREATE TABLE IF NOT EXISTS `intelliMerge_replication`.`conflicting_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `merge_tool` VARCHAR(45) NOT NULL,
  `path` VARCHAR(1000) NOT NULL,
  `total_conflicts` INT NOT NULL,
  `total_conflicting_loc` INT NOT NULL,
  `merge_result_id` INT NOT NULL,
  `merge_commit_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `merge_result_id`, `merge_commit_id`, `project_id`),
  INDEX `fk_conflicting_file_merge_result1_idx` (`merge_result_id` ASC, `merge_commit_id` ASC, `project_id` ASC),
  CONSTRAINT `fk_conflicting_file_merge_result1`
    FOREIGN KEY (`merge_result_id` , `merge_commit_id` , `project_id`)
    REFERENCES `intelliMerge_replication`.`merge_result` (`id` , `merge_commit_id` , `project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intelliMerge_replication`.`conflict_block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intelliMerge_replication`.`conflict_block` ;

CREATE TABLE IF NOT EXISTS `intelliMerge_replication`.`conflict_block` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(1000) NOT NULL,
  `conflicting_loc` INT NOT NULL,
  `start_line` INT NOT NULL,
  `end_line` INT NOT NULL,
  `conflicting_file_id` INT NOT NULL,
  `merge_result_id` INT NOT NULL,
  `merge_commit_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `merge_result_id`, `merge_commit_id`, `project_id`, `conflicting_file_id`),
  INDEX `fk_conflict_block_conflicting_file1_idx` (`conflicting_file_id` ASC, `merge_result_id` ASC, `merge_commit_id` ASC, `project_id` ASC),
  CONSTRAINT `fk_conflict_block_conflicting_file1`
    FOREIGN KEY (`conflicting_file_id` , `merge_result_id` , `merge_commit_id` , `project_id`)
    REFERENCES `intelliMerge_replication`.`conflicting_file` (`id` , `merge_result_id` , `merge_commit_id` , `project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intelliMerge_replication`.`refactoring`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `intelliMerge_replication`.`refactoring` ;

CREATE TABLE IF NOT EXISTS `intelliMerge_replication`.`refactoring` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `refactoring_type` VARCHAR(100) NULL,
  `refactoring_detail` VARCHAR(2000) NULL,
  `commit_hash` VARCHAR(40) NULL,
  `merge_commit_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`, `merge_commit_id`, `project_id`),
  INDEX `fk_refactoring_merge_commit1_idx` (`merge_commit_id` ASC, `project_id` ASC),
  CONSTRAINT `fk_refactoring_merge_commit1`
    FOREIGN KEY (`merge_commit_id` , `project_id`)
    REFERENCES `intelliMerge_replication`.`merge_commit` (`id` , `project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
